name: Notify SMS Sanity
permissions:
  contents: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21.x', '1.22.x']
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Check go version
        run: go version

      - name: Go Format
        run: gofmt -s -w . && git diff --exit-code

      - name: Go Tidy
        run: go mod tidy && git diff --exit-code

      - name: Go Mod Verify
        run: go mod verify

      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-cache: true
          skip-pkg-cache: true
          skip-build-cache: true
      - name: Build
        run: go build -v .
      - name: Run tests
        run: |
          touch .env
          echo "NOTIFY_SMS_USERNAME=${{ secrets.NOTIFY_SMS_USERNAME }}" >> .env
          echo "NOTIFY_SMS_TEST_CONTACT=${{ secrets.NOTIFY_SMS_TEST_CONTACT }}" >> .env
          echo "NOTIFY_SMS_PASSWORD=${{ secrets.NOTIFY_SMS_PASSWORD }}" >> .env
          echo "NOTIFY_SMS_SENDER_ID=${{ secrets.NOTIFY_SMS_SENDER_ID }}" >> .env
          make tests